# Generated by Django 5.1 on 2025-03-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiadores',
            fields=[
                ('id_financiados', models.AutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qtd_membros', models.IntegerField()),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='execution.areastecnologicas')),
                ('id_colaboradores', models.ManyToManyField(related_name='colaboradores', to='execution.colaboradores')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='execution.financiadores')),
            ],
        ),
    ]
